services:
  - type: web
    name: wa-django-adapter
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: DJANGO_BASE_URL
        sync: false
      - key: DJANGO_AUTH_TOKEN
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"